const fs = require('fs');

const univMap = {
    "4년제 대학교": "4-Year University",
    "2~3년제 전문대학": "2~3-Year College",
    "기타 대학교": "Other University",
    "서울대학교": "Seoul National University",
    "연세대학교": "Yonsei University",
    "고려대학교": "Korea University",
    "서강대학교": "Sogang University",
    "성균관대학교": "Sungkyunkwan University",
    "한양대학교": "Hanyang University",
    "중앙대학교": "Chung-Ang University",
    "경희대학교": "Kyung Hee University",
    "한국외국어대학교": "Hankuk University of Foreign Studies",
    "서울시립대학교": "University of Seoul",
    "이화여자대학교": "Ewha Womans University",
    "건국대학교": "Konkuk University",
    "동국대학교": "Dongguk University",
    "홍익대학교": "Hongik University",
    "국민대학교": "Kookmin University",
    "숭실대학교": "Soongsil University",
    "세종대학교": "Sejong University",
    "단국대학교": "Dankook University",
    "명지대학교": "Myongji University",
    "상명대학교": "Sangmyung University",
    "가톨릭대학교": "The Catholic University of Korea",
    "덕성여자대학교": "Duksung Women's University",
    "동덕여자대학교": "Dongduk Women's University",
    "서울과학기술대학교": "Seoul National University of Science and Technology",
    "서울여자대학교": "Seoul Women's University",
    "성신여자대학교": "Sungshin Women's University",
    "한성대학교": "Hansung University",
    "서경대학교": "Seokyeong University",
    "삼육대학교": "Sahmyook University",
    "성공회대학교": "Sungkonghoe University",
    "추계예술대학교": "Chugye University for the Arts",
    "광운대학교": "Kwangwoon University",
    "서울교육대학교": "Seoul National University of Education",
    "한국예술종합학교": "Korea National University of Arts",
    "한국체육대학교": "Korea National Sport University",
    "감리교신학대학교": "Methodist Theological University",
    "장로회신학대학교": "Presbyterian University and Theological Seminary",
    "총신대학교": "Chongshin University",
    "강서대학교(KC대)": "Gangseo University (KC Univ)",
    "한국성서대학교": "Korean Bible University",
    "서울한영대학교": "Seoul Hanyoung University",
    "서울기독대학교": "Seoul Christian University",
    "디지털서울문화예술대학교": "Digital Seoul Culture Arts University",
    "사이버한국외국어대학교": "Cyber Hankuk University of Foreign Studies",
    "서울디지털대학교": "Seoul Digital University",
    "서울사이버대학교": "Seoul Cyber University",
    "기타 4년제 대학교": "Other 4-Year University",
    "명지전문대학": "Myongji College",
    "동양미래대학교": "Dongyang Mirae University",
    "인덕대학교": "Induk University",
    "서일대학교": "Seoil University",
    "배화여자대학교": "Baewha Women's University",
    "숭의여자대학교": "Soongeui Women's College",
    "한양여자대학교": "Hanyang Women's University",
    "서울여자간호대학교": "Seoul Women's College of Nursing",
    "삼육보건대학교": "Sahmyook Health University College",
    "백석예술대학교": "Baekseok Arts University",
    "정화예술대학교": "Jeonghwa Arts College",
    "국제예술대학교": "Kukje Theological University and Seminary",
    "기타 2~3년제 전문대학": "Other 2~3-Year College",
    "인하대학교": "Inha University",
    "인천대학교": "Incheon National University",
    "가천대학교": "Gachon University",
    "경기대학교": "Kyonggi University",
    "아주대학교": "Ajou University",
    "단국대학교(죽전)": "Dankook University (Jukjeon)",
    "성균관대학교(자연과학캠퍼스)": "Sungkyunkwan University (Natural Sciences)",
    "한양대학교(ERICA)": "Hanyang University (ERICA)",
    "경희대학교(국제)": "Kyung Hee University (Global)",
    "한국항공대학교": "Korea Aerospace University",
    "한국외국어대학교(글로벌)": "Hankuk University of Foreign Studies (Global)",
    "동국대학교(바이오메디)": "Dongguk University (Biomedi)",
    "강남대학교": "Kangnam University",
    "수원대학교": "University of Suwon",
    "용인대학교": "Yong In University",
    "한신대학교": "Hanshin University",
    "협성대학교": "Hyupsung University",
    "안양대학교": "Anyang University",
    "성결대학교": "Sungkyul University",
    "평택대학교": "Pyeongtaek University",
    "한경국립대학교": "Hankyong National University",
    "신한대학교": "Shinhan University",
    "을지대학교": "Eulji University",
    "차의과학대학교": "CHA University",
    "루터대학교": "Luther University",
    "대진대학교": "Daejin University",
    "인천가톨릭대학교": "Incheon Catholic University",
    "중부대학교(고양)": "Joongbu University (Goyang)",
    "청운대학교(인천)": "Chungwoon University (Incheon)",
    "한세대학교": "Hansei University",
    "화성의과학대학교(신경대)": "Hwaseong University of Science",
    "아세아연합신학대학교": "ACTS University",
    "예원예술대학교(양주)": "Yewon Arts University (Yangju)",
    "중앙승가대학교": "Joong-ang Sangha University",
    "서울신학대학교": "Seoul Theological University",
    "서울장신대학교": "Seoul Jangsin University",
    "경인교육대학교": "Gyeongin National University of Education",
    "인하공업전문대학": "Inha Technical College",
    "부천대학교": "Bucheon University",
    "동남보건대학교": "Dongnam Health University",
    "경기과학기술대학교": "Gyeonggi Institute of Science and Technology",
    "오산대학교": "Osan University",
    "수원과학대학교": "Suwon Science College",
    "경인여자대학교": "Kyung-in Women's University",
    "재능대학교": "JEIU University",
    "연성대학교": "Yeonsung University",
    "대림대학교": "Daelim University",
    "신구대학교": "Shingu College",
    "동서울대학교": "Dongnam Health University",
    "유한대학교": "Yuhan University",
    "장안대학교": "Jangan University",
    "안산대학교": "Ansan University",
    "여주대학교": "Yeoju Institute of Technology",
    "청강문화산업대학교": "Chungkang College of Cultural Industries",
    "한국관광대학교": "Korea Tourism College",
    "한국복지대학교": "Korea National University of Welfare",
    "경민대학교": "Kyungmin University",
    "서정대학교": "Seojeong University",
    "두원공과대학교": "Doowon Technical University",
    "농협대학교": "Nonghyup University",
    "용인예술과학대학교": "Yongin Arts & Science University",
    "계원예술대학교": "Kaywon University of Art and Design",
    "서울예술대학교": "Seoul Institute of the Arts",
    "동아방송예술대학교": "Dong-Ah Institute of Media and Arts",
    "김포대학교": "Kimpo University",
    "수원여자대학교": "Suwon Women's University",
    "용인송담대학교": "Yongin Songdam College",
    "웅지세무대학교": "Woongji Tax Accounting College",
    "인천재능대학교": "Incheon JEIU University",
    "부산대학교": "Pusan National University",
    "부경대학교": "Pukyong National University",
    "한국해양대학교": "Korea Maritime and Ocean University",
    "동아대학교": "Dong-A University",
    "동의대학교": "Dongeui University",
    "경성대학교": "Kyungsung University",
    "신라대학교": "Silla University",
    "인제대학교": "Inje University",
    "영산대학교": "Youngsan University",
    "동서대학교": "Dongseo University",
    "부산가톨릭대학교": "Catholic University of Pusan",
    "부산외국어대학교": "Busan University of Foreign Studies",
    "고신대학교": "Kosin University",
    "경상국립대학교": "Gyeongsang National University",
    "창원대학교": "Changwon National University",
    "경남대학교": "Kyungnam University",
    "울산대학교": "University of Ulsan",
    "울산과학기술원(UNIST)": "UNIST",
    "창신대학교": "Changshin University",
    "가야대학교": "Gaya University",
    "한국국제대학교": "International University of Korea",
    "부산교육대학교": "Busan National University of Education",
    "진주교육대학교": "Chinju National University of Education",
    "부산과학기술대학교": "Busan Institute of Science and Technology",
    "경남정보대학교": "Kyungnam College of Information & Technology",
    "동의과학대학교": "Dongeui Institute of Technology",
    "대동대학교": "Daedong College",
    "마산대학교": "Masan University",
    "연암공과대학교": "Yonam Institute of Technology",
    "동주대학교": "Dongju College",
    "부산여자대학교": "Busan Women's College",
    "거제대학교": "Geoje College",
    "김해대학교": "Gimhae College",
    "진주보건대학교": "Jinju Health College",
    "창원문성대학교": "Changwon Moonsung University",
    "춘해보건대학교": "Choonhae College of Health Sciences",
    "동원과학기술대학교": "Dongwon Institute of Science and Technology",
    "한국승강기대학교": "Korea Lift College",
    "울산과학대학교": "Ulsan College",
    "경북대학교": "Kyungpook National University",
    "영남대학교": "Yeungnam University",
    "계명대학교": "Keimyung University",
    "대구대학교": "Daegu University",
    "대구가톨릭대학교": "Catholic University of Daegu",
    "국립안동대학교": "Andong National University",
    "금오공과대학교": "Kumoh National Institute of Technology",
    "경운대학교": "Kyungwoon University",
    "경일대학교": "Kyungil University",
    "동국대학교(WISE)": "Dongguk University (WISE)",
    "김천대학교": "Gimcheon University",
    "대구한의대학교": "Daegu Haany University",
    "위덕대학교": "U1 University",
    "포항공과대학교(POSTECH)": "POSTECH",
    "한동대학교": "Handong Global University",
    "대구경북과학기술원(DGIST)": "DGIST",
    "영남신학대학교": "Youngnam Theological University and Seminary",
    "대신대학교": "Daeshin University",
    "대구교육대학교": "Daegu National University of Education",
    "영진전문대학교": "Yeungjin University",
    "대구보건대학교": "Daegu Health College",
    "대구과학대학교": "Taegu Science University",
    "계명문화대학교": "Keimyung College University",
    "경북전문대학교": "Kyungbuk College",
    "구미대학교": "Gumi University",
    "수성대학교": "Suseong College",
    "안동과학대학교": "Andong Science College",
    "호산대학교": "Hosan University",
    "선린대학교": "Sunlin University",
    "포항대학교": "Pohang College",
    "대경대학교": "Taekyeung College",
    "문경대학교": "Mungyong College",
    "가톨릭상지대학교": "Catholic Sangji College",
    "대구공업대학교": "Daegu Technical University",
    "영남이공대학교": "Yeungnam University College",
    "전남대학교": "Chonnam National University",
    "조선대학교": "Chosun University",
    "광주대학교": "Gwangju University",
    "호남대학교": "Honam University",
    "전북대학교": "Jeonbuk National University",
    "우석대학교": "Woosuk University",
    "원광대학교": "Wonkwang University",
    "전주대학교": "Jeonju University",
    "국립목포대학교": "Mokpo National University",
    "국립순천대학교": "Sunchon National University",
    "국립군산대학교": "Kunsan National University",
    "광주과학기술원(GIST)": "GIST",
    "동신대학교": "Dongshin University",
    "남부대학교": "Nambu University",
    "초당대학교": "Chodang University",
    "광주가톨릭대학교": "Gwangju Catholic University",
    "국립목포해양대학교": "Mokpo National Maritime University",
    "한국에너지공과대학교(KENTECH)": "KENTECH",
    "광주여자대학교": "Kwangju Women's University",
    "전주교육대학교": "Jeonju National University of Education",
    "광주교육대학교": "Gwangju National University of Education",
    "호원대학교": "Howon University",
    "예수대학교": "Jesus University",
    "한일장신대학교": "Hanil University and Presbyterian Theological Seminary",
    "광주신학대학교": "Gwangju Theological University",
    "광주보건대학교": "Gwangju Health University",
    "조선이공대학교": "Chosun College of Science and Technology",
    "기독간호대학교": "Christian College of Nursing",
    "원광보건대학교": "Wonkwang Health Science University",
    "전주비전대학교": "Jeonju Vision College",
    "동강대학교": "Dongkang College",
    "서영대학교": "Seoyeong University",
    "순천제일대학교": "Suncheon Jeil College",
    "동아보건대학교": "Donga Health College",
    "전남과학대학교": "Chunnam Techno University",
    "광양보건대학교": "Gwangyang Health Sciences College",
    "전북과학대학교": "Jeonbuk Science College",
    "군장대학교": "Kunjang University College",
    "백제예술대학교": "Paekche Institute of the Arts",
    "충남대학교": "Chungnam National University",
    "국립한밭대학교": "Hanbat National University",
    "한남대학교": "Hannam University",
    "목원대학교": "Mokwon University",
    "배재대학교": "Pai Chai University",
    "우송대학교": "Woosong University",
    "충북대학교": "Chungbuk National University",
    "청주대학교": "Cheongju University",
    "한국기술교육대학교(KOREATECH)": "KOREATECH",
    "순천향대학교": "Soonchunhyang University",
    "백석대학교": "Baekseok University",
    "선문대학교": "Sun Moon University",
    "호서대학교": "Hoseo University",
    "남서울대학교": "Namseoul University",
    "건양대학교": "Konyang University",
    "대전대학교": "Daejeon University",
    "국립공주대학교": "Kongju National University",
    "세명대학교": "Semyung University",
    "유원대학교": "U1 University",
    "한국교통대학교": "Korea National University of Transportation",
    "건국대학교(글로컬)": "Konkuk University (Glocal)",
    "고려대학교(세종)": "Korea University (Sejong)",
    "홍익대학교(세종)": "Hongik University (Sejong)",
    "극동대학교": "Far East University",
    "서원대학교": "Seowon University",
    "단국대학교(천안)": "Dankook University (Cheonan)",
    "상명대학교(천안)": "Sangmyung University (Cheonan)",
    "나사렛대학교": "Korea Nazarene University",
    "꽃동네대학교": "Kkottongnae University",
    "금강대학교": "Geumgang University",
    "중원대학교": "Jungwon University",
    "청주교육대학교": "Cheongju National University of Education",
    "공주교육대학교": "Gongju National University of Education",
    "침례신학대학교": "Korea Baptist Theological University",
    "대전보건대학교": "Daejeon Health Institute of Technology",
    "대덕대학교": "Daeduk University",
    "충청대학교": "Chung Cheong University",
    "백석문화대학교": "Baekseok Culture University",
    "신성대학교": "Shinsung University",
    "연암대학교": "Yonam College",
    "대전과학기술대학교": "Daejeon Institute of Science and Technology",
    "아주자동차대학교": "Ajou Motor College",
    "한국영상대학교": "Korea University of Media Arts",
    "혜전대학교": "Hyejeon College",
    "충북도립대학교": "Chungbuk Provincial College",
    "충남도립대학교": "Chungnam State College",
    "대원대학교": "Daewon University College",
    "강원대학교": "Kangwon National University",
    "한림대학교": "Hallym University",
    "연세대학교(미래캠퍼스)": "Yonsei University (Mirae)",
    "상지대학교": "Sangji University",
    "국립강릉원주대학교": "Gangneung-Wonju National University",
    "제주대학교": "Jeju National University",
    "제주국제대학교": "Jeju International University",
    "가톨릭관동대학교": "Catholic Kwandong University",
    "경동대학교": "Kyungdong University",
    "한라대학교": "Halla University",
    "춘천교육대학교": "Chuncheon National University of Education",
    "한림성심대학교": "Hallym Polytechnic University",
    "강원도립대학교": "Gangwon Provincial College",
    "제주한라대학교": "Cheju Halla University",
    "제주관광대학교": "Jeju Tourism University",
    "한국골프대학교": "Korea Golf University",
    "송호대학교": "Songho College",
    "세경대학교": "Saekyung College",
    "송곡대학교": "Songgok College"
};

let en = JSON.parse(fs.readFileSync('src/locales/en/common.json', 'utf8'));

// Inject translations into the English JSON
for (let key in univMap) {
    if (en.profile_data[key] !== undefined) {
        en.profile_data[key] = univMap[key];
    }
}

fs.writeFileSync('src/locales/en/common.json', JSON.stringify(en, null, 2));
console.log('Successfully injected exact English names for universities!');
